### ISSUE TITLE
Generate COBOL Control Flow only shows the Nested Program, not the Main program that called it

### ISSUE THREAD

**Issue by RavenCot** [eclipse-che4z/che-che4z-lsp-for-cobol#1944] opened 2023-06-22 21:26 UTC
## Description ##

When editing a COBOL source file that contains Nested Programs  the right-click menu item "Generate COBOL Control Flow" generates a Control Flow of one of the nested programs - not the main program that calls the subprograms.
An example source and related documentation can be found at https://www.ibm.com/docs/en/cobol-zos/6.1?topic=programs-nested

## Steps to reproduce ##

1. Open the source file containing a main program and one or more nested programs.
2. Right-click anywhere in the source and select "Generate COBOL Control Flow" 
3. See that the Control Flow diagram is only generated for one of the subprograms.

## Expected behavior ##

I would expect to see the COBOL Control Flow diagram at least for the main program, or preferably for the whole collection of Main+Nested programs.

## Screenshots ##

![NestPgm](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/assets/137443084/85a348e0-f0c4-4c2b-8fd1-a450357b6cdf)

## Environment ##

 - OS: Windows Server 2022
 - IDE: VS Code

## Additional information ##

Sample COBOL source file is attached.
[NestPgm.txt](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/files/11840518/NestPgm.txt)

**Comment by VitGottwald** [comment] 2023-06-23 08:40
Duplicate of https://github.com/BroadcomMFD/cobol-control-flow/issues/39 .

**Closed as completed by VitGottwald** 2023-06-23 08:40 UTC
Labels: bug

**Comment by sundar-sarvam** [comment] 2023-08-14 07:57
Is the control flow graph implementation of [che-che4z-lsp-for-cobol](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol) not opensource? Why is it a duplicate of https://github.com/BroadcomMFD/cobol-control-flow/issues/39  which is not an opensoured tool

**Comment by zimlu02** [comment] 2023-08-14 15:12
[COBOL Control Flow ](https://github.com/BroadcomMFD/cobol-control-flow/issues)is a stand-alone extension that is not open-source. 
We do recommend using it in integration with [COBOL LS ](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol)extension but they are separate tools.
